### ISSUE TITLE
There are no tests

### ISSUE THREAD

**Issue by fidian** [tests-always-included/HealthCheckComponent#1]
For an organization named "tests-always-included" it is odd to see a repository with no tests.  There's not even any framework for those tests to live within.  :-(

However, it's only been one day so I assume that tests will be committed today, right?  :-)

**Comment by wjaspers** [comment]
Thats why the master branch is empty right now. I'm spending my own time rolling this from memory. Don't fret, though, tests WILL be included ;)

**Comment by wjaspers** [comment]
Tests are now provided ;)
