### ISSUE TITLE
Hook up Travis

### ISSUE THREAD

**Issue by fidian** [tests-always-included/HealthCheckComponent#2]
Travis can run the tests for this project automatically.  Check out http://docs.travis-ci.com/user/languages/php/ for more information.

**Comment by wjaspers** [comment]
Thanks for the link. I did take Travis into consideration earlier, but haven't gotten around to it quite yet. Maybe by the end of the week ;)

**Comment by wjaspers** [comment]
Completed! Thanks for the info, too.
https://travis-ci.org/tests-always-included/HealthCheckComponent
